# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dcb1cb8e2015933b8c660384c75ebeb53123a5bdc1d8929d31510ec471e5884aba5b7dcde5bc40c8316e330419a1b3ffe589ef2ceabcdd08c95dfed47f62151

test:
  secret_key_base: 3565b2775ef9941fcead47fccd2c52efbce17dfa5b96dc17083fcc0347a7334972d67d70a2a6ad5387c606779ee5fd857110bf7aa4f08bdd650ac959db92d296

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
